### ISSUE TITLE
Github pages' deployment doesn't work

### ISSUE THREAD

**Issue by benzlokzik** [datalens-tech/datalens-ui#131]
[Deployment page](https://datalens-tech.github.io/datalens-ui/) returns error 404

Here's the screenshot down below

![image](https://github.com/datalens-tech/datalens-ui/assets/121052717/85d592ef-2f6f-4d08-be26-f3e6e5b660c5)

**Comment by melikhov-dev** [comment]
Hi @benzlokzik! We don't have github pages for this repository.
