### ISSUE TITLE
Setting up locally getting errors

### ISSUE THREAD

**Issue by muhammadsalif-tps** [datalens-tech/datalens-ui#350]
Hi, I was trying to setting up this locally, I was following steps from the guide but getting this error.
`SETUP_DEV_ENV_INSTALLATION is not recognized as an internal or external command`
Attaching snapshot as well.
![image](https://github.com/datalens-tech/datalens-ui/assets/143704412/56c8c290-739c-48ff-89d6-75caf9edcf94)

**Comment by Marginy605** [comment]
Hi, could you tell us please more details about steps: what exactly command and in what folder are you trying to do this?

**Comment by muhammadsalif-tps** [comment]
Thanks for the response, I was trying to set up a datalens-ui repository
locally, i am running on a windows machine.
Steps i followed are as follows:
npm ci (that worked complete fine)
then i ran npm run dev Then i start getting lost of errors in command to
setting up this variable SETUP_DEV_ENV_INSTALLATION=opensource
then i solved this with cross-env package.
But, after solving this i got stucked in issue related to permission and
these client.sock or server.sock is not working i guess because of nginx
reverse proxy.
Attaching the error response below as well.
Thanks.
Would appreciate it if there is any other source of medium to contact you
than on email.

UNHANDLED EXCEPTION
Error +0ms
listen EACCES: permission denied D:\datalens-ui\dist\run\client.sock +0ms
Error: listen EACCES: permission denied D:\datalens-ui\dist\run\client.sock
    at Server.setupListenHandle [as _listen2] (node:net:1734:21)
    at listenInCluster (node:net:1799:12)
    at Server.listen (node:net:1898:5)
    at READ_WRITE
(D:\datalens-ui\node_modules\webpack-dev-server\lib\Server.js:3367:23)
    at new Promise (<anonymous>)
    at Server.start
(D:\datalens-ui\node_modules\webpack-dev-server\lib\Server.js:3365:7)
    at process.processTicksAndRejections
(node:internal/process/task_queues:95:5)
    at async buildWebpackServer
***@***.***\app-builder\dist\commands\dev\client.js:119:9)
    at async watchClientCompilation
***@***.***\app-builder\dist\commands\dev\client.js:39:31)
    at async default_1
***@***.***\app-builder\dist\commands\dev\index.js:84:29)
+0ms
Exit with code: 1

**Comment by Marginy605** [comment]
Thanks for details! Yes, there is a known problem with launching in some Windows OS versions. We recommend to use WSL2 and setup nginx as workaround.
We'll try to solve problem with sockets but it will take some time.

**Comment by muhammadsalif-tps** [comment]
Related to this I am facing another issue while connecting my database(PostgreSQL). 
I am running this (datalens project) on my wsl2. How can I able to connect my PostgreSQL database to it ? Should I run PostgreSQL server on wsl2 as well? Or I can connect this via remote connection on my Windows machine. 
I've tried both and getting errors, still unable to connect to DB :(

**Comment by Marginy605** [comment]
We need some time to check how we could help with your problem. We will return with more details a little bit later.

**Comment by melikhov-dev** [comment]
duplicate https://github.com/datalens-tech/datalens/issues/69
